### ISSUE TITLE
how to use them?

### ISSUE THREAD

**Issue by hz2018tv** [K11MCH1/AdrenoToolsDrivers#11]
Hi, I tried to load alternative gpu drivers on android 13 ( Snapdraon 6 Gen 1 w/ Adreno 710 ). The qualcomm drivers load fine, but all mesa turnip drivers close yuzu / skyline immediately. The debug log shows the last error was VK_LAYER_KHRONOS_validation not available. How to use the mesa turnip drivers? thx

**Comment by aatri2021** [comment]
https://developer.android.com/ndk/guides/graphics/validation-layer
i'm guessing its not the drivers you just need the validation layer so added to your build or just turn off the validation layer
