### ISSUE TITLE
Meta quest 3 r728 driver for adreno 7xx series?

### ISSUE THREAD

**Issue by oscarbg** [K11MCH1/AdrenoToolsDrivers#17]
Hi,
Just seen on vulkan info new meta quest 3 ships with 728 driver for an adreno 740 gpu..
Hope this driver can be posted if is usable at least for 7xx series on yuzu..
Thanks..

**Comment by K11MCH1** [comment]
> Hi,
> Just seen on vulkan info new meta quest 3 ships with 728 driver for an adreno 740 gpu..
> Hope this driver can be posted if is usable at least for 7xx series on yuzu..
> Thanks..

Thanks for letting me know.
I'll investigate :)

**Comment by oscarbg** [comment]
Thanks! Hoping the best..

**Comment by oscarbg** [comment]
Friendly ping.. have time to investigate?

**Comment by K11MCH1** [comment]
> Friendly ping.. have time to investigate?

We did some internal testing with it and concluded they're too broken for Emulators to be used.
Stuff like whole app UI and OS UI (when minimized) glitching.

**Comment by oscarbg** [comment]
thanks!! closing..

**Comment by CADIndie** [comment]
> > Friendly ping.. have time to investigate?
> 
> We did some internal testing with it and concluded they're too broken for Emulators to be used. Stuff like whole app UI and OS UI (when minimized) glitching.

While it was known that it was broken, is there an understanding of why at the moment?
