### ISSUE TITLE
Adreno r744 driver seen on vulkaninfo for adreno 7xx series?

### ISSUE THREAD

**Issue by oscarbg** [K11MCH1/AdrenoToolsDrivers#18]
Hi,

Just seen on vulkaninfo first adreno 750 device with 744 driver for this adreno 750 gpu..
http://vulkan.gpuinfo.org/displayreport.php?id=25155
Hope this driver is extracted from some new adreno 750 device ROM soon enough, and it's usable at least for 7xx series on yuzu..
may take a while to find this drivers but posting so I keep notified in case you can release it..

Thanks..

**Comment by oscarbg** [comment]
Hi,
sorry to update, but seems 744.4 is out for everybody to try as shown on vulkan info tested on Adreno 730,740,etc.. .. hope you can release soon..
NOTE: please consider releasing this one, even if it's somewhat buggy like the previously 728 you tested and didn't release.. it's Adreno 750 launch driver and also may fix bugs in unexpected places on games..

**Comment by K11MCH1** [comment]
> Hi, sorry to update, but seems 744.4 is out for everybody to try as shown on vulkan info tested on Adreno 730,740,etc.. .. hope you can release soon.. NOTE: please consider releasing this one, even if it's somewhat buggy like the previously 728 you tested and didn't release.. it's Adreno 750 launch driver and also may fix bugs in unexpected places on games..

Feel free to let me know when you find a source.

**Comment by oscarbg** [comment]
Thanks, will do..

**Comment by K11MCH1** [comment]
> Thanks, will do..

I already found it. However its also not working just like 728.
Need to wait for a fix from the dev of Bylaws since these drivers are completely different than what we've been dealing with before.

**Comment by oscarbg** [comment]
Hi,
thanks for sharing your findings!.. it sad to hear new drivers need "new mods".. 
hope at least he is aware of the issues you have found and willing to work on it..
