### ISSUE TITLE
Revision 9?

### ISSUE THREAD

**Issue by djdp77** [K11MCH1/AdrenoToolsDrivers#19]
@K11MCH1 From Danylo's repository: https://gitlab.freedesktop.org/Danil/mesa/-/tree/turnip/feature/a730-variant-support

This should work on all A730 and A725, or at least help troubleshooting it. Rev8 does not work on A725 at least

**Comment by K11MCH1** [comment]
> @K11MCH1 From Danylo's repository: https://gitlab.freedesktop.org/Danil/mesa/-/tree/turnip/feature/a730-variant-support
> 
> This should work on all A730 and A725, or at least help troubleshooting it. Rev8 does not work on A725 at least

This is already in R8.

**Comment by djdp77** [comment]
I suggested a new version since Danil made commits after Rev8

**Comment by K11MCH1** [comment]
> I suggested a new version since Danil made commits after Rev8

They're the same changes. I even made a test build to make sure and the results were same.

**Comment by djdp77** [comment]
The same for 8+gen1 / 7+gen2 as well? If yes i'll close this, just can't Turnip to work with Yuzu I guess

**Comment by djdp77** [comment]
Do you know if this just 7+gen2 or also 8+gen1? Or even broader than this?
