### ISSUE TITLE
OnePlus 10t 8gen1+ still crashing with the new driver v23.3.0_R8 

### ISSUE THREAD

**Issue by gongo1440** [K11MCH1/AdrenoToolsDrivers#20]
Still having crashing with the R8 driver I can't load any games

**Comment by Y0ung5m4ll** [comment]
Zenfone 9 also

**Comment by JKIT80** [comment]
Galaxy tab s8  Ultra isn't working.

**Comment by djdp77** [comment]
Is it crashing on Yuzu or also Dolphin/others? And if only Yuzu, does it also happen with older versions? (like the one on Playstore)

**Comment by JKIT80** [comment]
I haven't been in the scene for very long.  
I do seem to be having better luck with out using GPU drivers.  That could be user error though.  

Mario Wonder - grayed out on map
Luigi's Mansion 3 - lots of glitches
Mario Odyssey - all sorts of issues
Nintendo 64 Games - Can't get past initial load

Mario Deluxe U -  Seems Good
Sonic -  Works very well

3 switches in the house with family plans and always purchase games in multiples of three.  

All I want to do is leave my switch at home and play on the tablet I have bring with for work when I travel. 

The progress on this is amazing though.  Purchased the upgraded yuzu to support.

**Comment by djdp77** [comment]
@JKIT80 try out Rev9 with Yuzu Android-117. If that does not help try Qualcomm 676.42 as that as worked better for me

**Comment by danfozzy** [comment]
Crashing with a samsung fold 4 (8gen1+) R8 and R9. Not matter the yuzu version (tried github releases 122 all the way back to 81 & yuzu EA playstore version)

**Comment by djdp77** [comment]
@danfozzy weird that it does not work with yuzu81. Did games work with qualcomm drivers? And if you try these drivers on dolphin do they work?

**Comment by gongo1440** [comment]
Thanks K11MCH1 with the new driver run perfect with yuzu beta one plus 10t❤️❤️
