### ISSUE TITLE
Samsung 23plus SD 8 Gen 2 lag/unstable games/crash

### ISSUE THREAD

**Issue by jumznatic** [K11MCH1/AdrenoToolsDrivers#22]
Hello, still cant play some games on my samsung galaxy s23 plus Snapdragon 8 gen 2. Hope there's a stable driver for this device. Ty

**Comment by K11MCH1** [comment]
Try adding the emulators to Samsung GOS (Game optimizing service).
Or completely disable GOS.
Another workaround is using a frontend like DIG.
