### ISSUE TITLE
Zenfone 9(8+ gen 1) still crashing on yuzu with R9

### ISSUE THREAD

**Issue by Y0ung5m4ll** [K11MCH1/AdrenoToolsDrivers#23]
So all of my games still crashing on yuzu with Mesa Turnip Driver v23.3.0 - R9

I also tried the driver from Mr Purple, it works! I am able to play Super Mario Odyssey and Diablo III with it. With Qualcomm drivers v676.4 I am able to get into these two games but only colors.

Nevertheless, I am still not able to play any of my games with the latest mesa driver and yuzu

Does that means 8GB Ram really not enough to play yuzu with proper driver or there is something still need to be fixed?

Thanks

**Comment by gongo1440** [comment]
I have the same problem one plus 10t still Crashing with this driver.

**Comment by djdp77** [comment]
@Y0ung5m4ll @gongo1440 which version of Yuzu did you use? And which drivers from mrpurple?

**Comment by gongo1440** [comment]
Yuzu v121 drivers R8,R9 and still having Crashing

**Comment by djdp77** [comment]
@gongo1440 ok, couldnyou test Yuzu android-81? It should work with that version

Additionally it would be great if you could test default drivers and R5 from here on Yuzu v121 and v81

Trying to understand where the problem comes from

**Comment by Y0ung5m4ll** [comment]
@djdp77 I am using v121 and the driver is from https://drive.google.com/file/d/1F-m63qv7x8uhnHm8ucKmnSFyOUeB4_n1/view?usp=drivesdk

**Comment by gongo1440** [comment]
This driver R8-R9 only work in my case with yuzu Playstore version run perfect.

**Comment by Y0ung5m4ll** [comment]
@djdp77 thanks v81 works with R9 and R5 but v121 doesn't work with R5

**Comment by djdp77** [comment]
@Y0ung5m4ll yes thats the expected behaviour, I've pinged the Yuzu team about this regression. Does it work with the one from MrPurple or not in v121?

Btw thats an old MrPurple build, you can find the latest here: https://t.me/s/MrPurpleProjects (requires a telegram account)

@gongo1440 your results surprised me though, could you reconfirm R5 works on v121 but not R8/9? Does this happen for all games?

**Comment by gongo1440** [comment]
Yes only R5 works on v121 for me. R8/9 they do not.

**Comment by Y0ung5m4ll** [comment]
@djdp77 yes Mr Purple's latest driver from the telegram works with v121

**Comment by Y0ung5m4ll** [comment]
@djdp77 Also I noticed that after I play yuzu, my phone's video playback is lagging

I guess it's driver's issue? Cuz it never happened before

**Comment by gongo1440** [comment]
Try with the new driver  is working perfect in my phone now

**Comment by Y0ung5m4ll** [comment]
Thanks R10 really works close this issue now
