### ISSUE TITLE
support 8 gen 3 for xiaomi 14

### ISSUE THREAD

**Issue by cheft** [K11MCH1/AdrenoToolsDrivers#24]
support 8 gen 3 for xiaomi 14

**Comment by atlusjack** [comment]
I have the same problem

**Comment by bibibivlin** [comment]
The A750 of Snapdragon 8 Gen 3 currently cannot display any content properly on Yuzu and can only output a black screen (but it can input operations and play soundtracks and sound effects).

**Comment by bibibivlin** [comment]
The A750 of Snapdragon 8 Gen 3 currently cannot display any content properly on Yuzu and can only output a black screen (but it can input operations and play soundtracks and sound effects).

**Comment by xunoni** [comment]
I confirm only black screen with xiaomi 14.
multiple firmwares and apps have been tested
Same result

**Comment by jasonxcx** [comment]
same problem

**Comment by K11MCH1** [comment]
There is no support for 8gen3 as of this moment. Please refrain from creating issues for this soc until there is support from Mesa.
