### ISSUE TITLE
adreno 725 is not supported by turnip

### ISSUE THREAD

**Issue by Vivek1661** [K11MCH1/AdrenoToolsDrivers#26]
Can you make adreno 725 supported to turnip

Device name :- POCO F5 5G
Ram :- 12GB
Processer :- Snapdragon 7+ Gen 2

**Comment by Ishan0981** [comment]
It's Fixed In Turnip Revision 9, You can Check It By Clicking This : <a href="https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/v23.3.0_R9">Click Here</a>

**Comment by K11MCH1** [comment]
Should be fixed now with Revision 10 (R-X).
