### ISSUE TITLE
V707 and v695 drivers?

### ISSUE THREAD

**Issue by oscarbg** [K11MCH1/AdrenoToolsDrivers#3]
Hi,
Great project!
Seems vulkan.gpuinfo.org reports with drivers versions 707 and 695 have started appearing like:
https://vulkan.gpuinfo.org/displayreport.php?id=20733
Would be nice to test
Thanks..

**Comment by K11MCH1** [comment]
> Hi, Great project! Seems vulkan.gpuinfo.org reports with drivers versions 707 and 695 have started appearing like: https://vulkan.gpuinfo.org/displayreport.php?id=20733 Would be nice to test Thanks..

707 has already been tested by our testers.
Can only work flashed as system.

**Comment by K11MCH1** [comment]
@oscarbg can you link v695?
Dont see it on vulkan gpuinfo.

**Comment by oscarbg** [comment]
695 link:
http://vulkan.gpuinfo.org/displayreport.php?id=19196

**Comment by K11MCH1** [comment]
> 695 link: http://vulkan.gpuinfo.org/displayreport.php?id=19196

That's fake driver.
Yigit is a known scammer and has been kicked out from telegram groups.

**Comment by oscarbg** [comment]
ok! thanks for info..
