### ISSUE TITLE
Mesa Turnip Driver v24.0.0 - Revision X (glitch oceanhorn2)

### ISSUE THREAD

**Issue by jumznatic** [K11MCH1/AdrenoToolsDrivers#35]
I tried this driver on oceanhorn 2 game, have glitch effect But good thing is slightly increase performance. Hoping for next update of drivers 😊

**Comment by Ishan0981** [comment]
> I tried this driver on oceanhorn 2 game, have glitch effect But good thing is slightly increase performance. Hoping for next update of drivers 😊

First you need to inform the emulator team, after informing if they suggest you create issue on this repo then only create.
