### ISSUE TITLE
Snapdragon 855 crashes on the menu of sonic superstars

### ISSUE THREAD

**Issue by Idk1245** [K11MCH1/AdrenoToolsDrivers#36]
Happened to me since 6xx got supported

**Comment by K11MCH1** [comment]
> Happened to me since 6xx got supported

Ask the emulator devs. I cant get anything fixed myself without knowing whats the problem. Also its not always a driver issue. Ask emu devs first please.

**Comment by Idk1245** [comment]
Will do and thanks for responding
