### ISSUE TITLE
Does the latest version support Qualcomm gen3?

### ISSUE THREAD

**Issue by yingnierxiao** [K11MCH1/AdrenoToolsDrivers#39]

**Comment by K11MCH1** [comment]
> 

No. There is partial support now but needs more work. Maybe next version.

**Comment by yingnierxiao** [comment]
How long will the next version take? I'm looking forward to it

**Comment by Ishan0981** [comment]
> How long will the next version take? I'm looking forward to it

You will be informed when it'll ready
