### ISSUE TITLE
Error with poco f3

### ISSUE THREAD

**Issue by Rorocode911** [K11MCH1/AdrenoToolsDrivers#4]
Hello, your project is awesome, and I love your drivers ! But I have many vulkan errors with turnip v23.0.2 in yuzu, with my poco f3.
Errors say device don't support this extension. What is the problem ? #

**Comment by Rorocode911** [comment]
My device have already a snapdragon 870 with adreno 650 and 8gb RAM 😭😭

**Comment by oDEVU** [comment]
For me updating system driver to newer one fixed a lot of theese errors. I think this might be just old system driver issue.

**Comment by alexyz-0** [comment]
v23.0.3 worked on my Poco F3 well. Tested a few games in Yuzu
