### ISSUE TITLE
There are still issues

### ISSUE THREAD

**Issue by darthkyria** [K11MCH1/AdrenoToolsDrivers#43]
I'm still getting frezze in kingdom of amalur re reckoning at the begining. I have tested in yuzu lastest versión of Google store (both paid and free versions).
[yuzu_log.txt](https://github.com/K11MCH1/AdrenoToolsDrivers/files/13444113/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/K11MCH1/AdrenoToolsDrivers/files/13444114/yuzu_log.txt.old.txt)

**Comment by darthkyria** [comment]
The paid version was more faster however good fps even with my snapdragon 870, Adreno 650 gpu

**Comment by Ishan0981** [comment]
> I'm still getting frezze in kingdom of amalur re reckoning at the begining. I have tested in yuzu lastest versión of Google store (both paid and free versions). [yuzu_log.txt](https://github.com/K11MCH1/AdrenoToolsDrivers/files/13444113/yuzu_log.txt) [yuzu_log.txt.old.txt](https://github.com/K11MCH1/AdrenoToolsDrivers/files/13444114/yuzu_log.txt.old.txt)

its not always a driver issue.
First you need to inform the emulator team, after informing them, if they suggest you to create issue on this repo then only create.

**Comment by swithun-liu** [comment]
same problem

**Comment by K11MCH1** [comment]
> I'm still getting frezze in kingdom of amalur re reckoning at the begining. I have tested in yuzu lastest versión of Google store (both paid and free versions).
> [yuzu_log.txt](https://github.com/K11MCH1/AdrenoToolsDrivers/files/13444113/yuzu_log.txt)
> [yuzu_log.txt.old.txt](https://github.com/K11MCH1/AdrenoToolsDrivers/files/13444114/yuzu_log.txt.old.txt)
> 

This is not yuzu.
Report this to Yuzu with these logs.
