### ISSUE TITLE
Driver issue

### ISSUE THREAD

**Issue by shakirali71** [K11MCH1/AdrenoToolsDrivers#44]
I am playing Assassin creed black flag but shodows not render and some performance issue plz fix that

**Comment by K11MCH1** [comment]
> I am playing Assassin creed black flag but shodows not render and some performance issue plz fix that

I dont fix anything.
Report issues to the emulator repo instead.

**Comment by BkxEmu** [comment]
Super Mario Wonder, with some slight FPS drops on the F5 with Snapdragon 7+ gen2

**Comment by shakirali71** [comment]
Plz fix bat arhkam city and arkham aslyum graphical glitch when hitting
puch or throwing batrang
