### ISSUE TITLE
New driver for yuzu 

### ISSUE THREAD

**Issue by MD0301** [K11MCH1/AdrenoToolsDrivers#45]
I think is about time that they should release a new driver like I know it's working for tons of games but the new driver should have come by now,am still waiting for it since 2 weeks +

**Comment by Venvvs** [comment]
> I think is about time that they should release a new driver like I know it's working for tons of games but the new driver should have come by now,am still waiting for it since 2 weeks +

Check again! 😂

**Comment by Venvvs** [comment]
I would close this as its not really an issue and more impatience I'm eager to get everything running flawlessly too but you must let them do what they need to do in order for that to happen.
