### ISSUE TITLE
Adreno 5xx Support for Turnip Drivers?

### ISSUE THREAD

**Issue by OkyDooky** [K11MCH1/AdrenoToolsDrivers#9]
I'm using Dolphin to try and play GameCube games on my Android phone. The regular Qualcomm driver from the Releases page works fine and seems to have made a noticeable improvement to the framerate and stability of the emulation. But, the Mesa Turnip drivers haven't worked for me, at all.
I get the following toast messages/errors when trying to launch a game after selecting the Turnip driver in the Graphics Settings:
`No Vulkan physical devices found`
`Failed fo initialize video backend`
I am using a Moto G7 Power with the latest Lineage 20 (Android 13) official release (the MicroG version). The chipset is a Snapdragon 632 (Adreno 506)
I thought it would support my device, because I was confusing the Snapdragon series for the Adreno series. Apparently, when it says "only for Adreno 6xx series" it means it.
Would it be possible to see a Turnip release that supports my device? When Dolphin released the blog update about supporting Adreno tools, the main example they gave was using the Turnip driver and how much it improved things in some circumstances. I'm grateful that I found this repo, because it has really made a bit more than "bearable" to try to play on my medoum-low end device, but I'd love to experience all the performance benefits I can.

Thanks for all the work you've done to help people be able to play more things better on their devices!

**Comment by OkyDooky** [comment]
>Would it be possible to see a Turnip release that supports my device?

To clarify: while I *would* like to request this to come to fruition, when I ask if it is possible, I mean is it even possible for Turnip to be compiled or otherwise made to support the Adreno 5xx series in the first place?

**Comment by OkyDooky** [comment]
How come?

**Comment by OkyDooky** [comment]
> clearly stated

Yeah, I wasn't going to find that readme anytime soon.
Well, that sucks. It doesn't sound like it's impossible, which is what I asked, but that no one is willing?
According to [this article](https://www.cnx-software.com/2019/03/15/turnip-open-source-vulkan-driver-adreno-gpu/), it deems that Turnip was maybe originally targeting the 5xx series. Maybe that got dropped?

**Comment by OkyDooky** [comment]
How much do you think that would cost? And you said "write" as in something from scratch and not an extended compatibility to an existing one like Turnip? Or is the latter what you meant?

One of the Qualcomm releases (690, I think) from this repo works on my chipset just fine, but it sounds like Turnip does some extra cool stuff, which is why I care at all.

I'd probably be willing, if it was in my financial ability and if it wouldn't cost much to maintain via updates.

**Comment by marcemira** [comment]
> I'd probably be willing, if it was in my financial ability and if it wouldn't cost much to maintain via updates.

It's very nice to have people willing to support open source development to increase the support on older devices, but frankly and AFAIK, it's not so worthy... Adreno 5xx is just too old to see any real benefits, and also, probably cheaper for you to just get a much powerful phone! Hope that helps.

**Comment by OkyDooky** [comment]
To me, the point of projects like Lineage is not to just have Android without Google spyware, but to also not need to constantly be upgrading your device.
I agree it would likely be cheaper, but being able to give a bit of extra juice to older chipsets may help a lot of people not need to upgrade their devices for a while longer. Again, I'm happy with the improvements the regular Qualcomm extracted driver gave in Dolphin, but the more the better and even moreso if it can help a lot of other people.

I'll probably be upgrading my phone in the next few years, but I already went through a really long journey of shopping and trial and error, earlier this year, and I'm happy with maximizing what I already have (Android 13 via Lineage, better photos via GCam, and now emulation), for now.

And, you're right: it may not even be worth it for these chipsets, as the performance may be so minimal and not worth the cost to support them. But, honestly, that's what I was hoping to find out in practice. Thanks for the helpful response.

**Comment by OkyDooky** [comment]
Looking further, it seems that "regular" Freedreno supports older chipsets, but I can't get much further than that. Other than Turnip being explicitly Vulkan-based, is there much difference between the two? Is "vanilla" Freedreno even still being developed? Is there a way to acquire releases like I can from here? If "yes," i'll probably change the issue name to match.

**Comment by LuiFernm** [comment]
Excuse me, the snapdragon 820 or 835 are high-end adreno 5xx processors, they are superior to several adreno 6xx processors like the snapdragon 662, 665, 670, 675, 710, 712, and the 680, there is no chance to launch for these old but powerful processors

**Comment by pixeldedaad1** [comment]
but what are the probably where is possible modify/customize the latest adreno 5xx driver v@0490.0? and for some lucky discover is possible transform it in a v@0665.0 driver? put the new things what have on latest turnip drivers 23.x and finally improve the emulator running in a old device instead a powerful one what no need to more nothing. i apologize for my english rich people from amerikan
